# Generated by Django 4.0.2 on 2022-02-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
